import type { Tier } from '../../storage/types.js';
import type { MockResponse } from '../../target/types.js';

/** The three tiers a scaffolded suite always provisions, in execution order. */
export const TIERS: Tier[] = ['tierA-public', 'tierB-auth', 'tierC-api'];

/**
 * Write-through per-test checkpoint file (see checkpointReporterContents()),
 * read back by execute.ts to resume mid-suite after an interruption. Lives at
 * the suite's project root, alongside results.json — not under fixtures/.
 */
export const EXEC_CHECKPOINT_FILENAME = 'healix-exec-checkpoint.ndjson';

/** `--test-list-invert` file execute.ts builds from EXEC_CHECKPOINT_FILENAME's entries before a resumed run. */
export const EXEC_CHECKPOINT_INVERT_FILENAME = 'healix-completed-tests.txt';

/** Map a tier id to a short, human-readable label (used in READMEs / comments). */
export function tierLabel(tier: Tier): string {
  switch (tier) {
    case 'tierA-public':
      return 'Tier A — Public (no auth)';
    case 'tierB-auth':
      return 'Tier B — Authenticated (per-role)';
    case 'tierC-api':
      return 'Tier C — API / backend';
    default:
      return String(tier);
  }
}

/** Pinned versions so the exported suite is reproducible without the monorepo. */
const PLAYWRIGHT_TEST_VERSION = '^1.49.0';

export interface PackageJsonOptions {
  name?: string;
}

/** package.json for a standalone, runnable Playwright project. */
export function packageJsonContents(opts: PackageJsonOptions = {}): string {
  const pkg = {
    name: opts.name ?? 'healix-suite',
    version: '0.0.0',
    private: true,
    description: 'Playwright test suite generated by Healix.',
    type: 'module',
    scripts: {
      test: 'playwright test',
      'test:tierA': 'playwright test --project=tierA-public',
      'test:tierB': 'playwright test --project=tierB-auth',
      'test:tierC': 'playwright test --project=tierC-api',
      report: 'playwright show-report',
    },
    devDependencies: {
      '@playwright/test': PLAYWRIGHT_TEST_VERSION,
    },
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

export interface ConfigOptions {
  baseUrl?: string | null;
}

/**
 * playwright.config.ts wiring the three Healix tiers as Playwright projects,
 * a JSON + HTML reporter, and the artifact policy: every test — passed or
 * failed — records a screenshot, video, and trace, so the run detail can
 * always show full evidence and not just what happened on failures. Tier B
 * depends on an auth storageState produced by fixtures/auth.setup.ts; when no
 * credentials are wired the setup is a no-op and Tier B specs simply run
 * unauthenticated.
 */
export function playwrightConfigContents(opts: ConfigOptions = {}): string {
  const baseUrl = (opts.baseUrl ?? '').trim();
  // Always honor the HEALIX_BASE_URL env override, even when a literal default is baked in.
  const baseUrlLiteral = baseUrl
    ? `process.env.HEALIX_BASE_URL || ${JSON.stringify(baseUrl)}`
    : "process.env.HEALIX_BASE_URL || 'http://localhost:3000'";

  return `import { defineConfig, devices } from '@playwright/test';
import { cpus, freemem } from 'node:os';

/**
 * Healix-generated Playwright config.
 * Projects mirror the Healix tiers; edit baseURL via HEALIX_BASE_URL or below.
 */

// Workers are sized to the machine's own headroom instead of a fixed number:
// this suite runs on the user's own desktop (often alongside their IDE/
// browser/other apps, not a dedicated CI runner), so saturating every core or
// every free byte of RAM would make the whole machine sluggish mid-run rather
// than just finishing tests faster. Leaves one core free for the OS/host app,
// and bounds by free RAM since each worker launches its own Chromium instance
// (memory-hungry, especially with video/trace recording always on — see the
// \`use\` block below). CI keeps a fixed worker count instead of trusting
// os.cpus()/os.freemem() — containerized CI runners often report the HOST's
// full capacity while only being allotted a cgroup-limited slice of it.
function computeWorkers() {
  const cpuCount = cpus().length;
  const freeMemGB = freemem() / 1024 ** 3;
  const GB_PER_WORKER = 0.75; // headed Chromium + video/trace recording, empirically ample
  const cpuBound = Math.max(1, cpuCount - 1);
  const memBound = Math.max(1, Math.floor(freeMemGB / GB_PER_WORKER));
  return Math.max(1, Math.min(cpuBound, memBound));
}

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  // Retries drive Healix's flaky detection (a test must fail then pass on retry
  // to register as flaky). Default to 1 locally too — gating on CI meant flaky
  // was never detectable on a local \`healix run\`. Override with HEALIX_RETRIES.
  retries: process.env.HEALIX_RETRIES ? Number(process.env.HEALIX_RETRIES) : process.env.CI ? 2 : 1,
  workers: process.env.CI ? 1 : computeWorkers(),
  timeout: 60_000,
  expect: { timeout: 10_000 },
  reporter: [
    ['json', { outputFile: 'results.json' }],
    ['html', { open: 'never' }],
    ['list'],
    // Playwright's own json reporter doesn't serialize step-level detail at
    // all (only overall status/duration/error/attachments) — this custom
    // reporter reads it straight off the live TestResult the Reporter API
    // exposes and writes it to steps.json, so the run detail can show what a
    // test actually did (clicked, filled, navigated, asserted...) step by
    // step, for passed tests too, not just failures.
    ['./fixtures/steps-reporter.cjs'],
    // Write-through per-test checkpoint (see fixtures/checkpoint-reporter.cjs's
    // own doc comment) — lets an interrupted run resume by skipping only the
    // tests that already finished, instead of redoing the whole suite. This is
    // also what makes it safe for all three tiers to run in a single combined
    // invocation below (instead of one Playwright process per tier): a crash
    // mid-run no longer loses per-tier progress, since progress is now tracked
    // per test regardless of which tier(s) were still in flight together.
    ['./fixtures/checkpoint-reporter.cjs'],
  ],
  use: {
    baseURL: ${baseUrlLiteral},
    screenshot: 'on',
    video: 'on',
    trace: 'on',
  },
  projects: [
    {
      name: 'auth-setup',
      // Override the inherited testDir ('./tests') so the setup file under
      // ./fixtures is actually discovered by testMatch.
      testDir: '.',
      testMatch: /fixtures\\/auth\\.setup\\.ts/,
    },
    {
      name: 'tierA-public',
      testDir: './tests/tierA-public',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'tierB-auth',
      testDir: './tests/tierB-auth',
      use: {
        ...devices['Desktop Chrome'],
        storageState: 'fixtures/.auth/user.json',
      },
      dependencies: ['auth-setup'],
    },
    {
      name: 'tierC-api',
      testDir: './tests/tierC-api',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
`;
}

/**
 * Custom Playwright reporter that captures step-level detail (clicks, fills,
 * navigations, assertions...) for every test — pass or fail — and writes it
 * to steps.json. Written as CommonJS (.cjs) regardless of the scaffolded
 * suite's "type": "module" so Playwright can always require() it directly,
 * with no transpilation step of its own.
 *
 * WHY a custom reporter instead of reading the built-in json reporter's
 * output: that reporter's TestResult serialization only includes overall
 * status/duration/error/attachments — no steps array at all. The Reporter
 * API's LIVE onTestEnd(test, result) callback, however, does expose
 * `result.steps` — this just persists that to disk before the process exits.
 *
 * Kept categories: 'test.step' (a generated spec's own human-authored
 * test.step('Enter email address', ...) wrapper — see generate.ts's prompt —
 * takes priority when present, since Playwright nests the raw pw:api/expect
 * calls INSIDE it as children, not as top-level entries, so only the
 * descriptive wrapper title surfaces here), plus 'pw:api' (real page actions)
 * and 'expect' (assertions) as a fallback for any action a spec didn't wrap.
 * 'hook'/'fixture' steps are Healix's own plumbing (auth setup, mock
 * routing) and not something a viewer needs to see per-test.
 */
export function stepsReporterContents(): string {
  return `const fs = require('node:fs');
const path = require('node:path');

const KEPT_CATEGORIES = new Set(['test.step', 'pw:api', 'expect']);
// Playwright's step error messages carry terminal color escape codes by
// default (e.g. \\u001b[2m) — verified live against a real failing step; left
// unstripped they render as garbled control characters in the report/UI.
const ANSI_RE = /[\\u001b\\u009b][[\\]()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g;
function stripAnsi(text) {
  return (text || '').replace(ANSI_RE, '');
}

function toStepItem(s) {
  // Only a test.step(...) wrapper gets its raw actions nested underneath —
  // a bare pw:api/expect step (no test.step wrapping) has no useful children
  // of its own, just the same kind of entry, so nesting there would just be
  // a step wrapping an identical copy of itself.
  const children =
    s.category === 'test.step'
      ? (s.steps || []).filter((c) => c.category === 'pw:api' || c.category === 'expect').map(toStepItem)
      : undefined;
  return {
    title: s.title,
    durationMs: Math.round(s.duration || 0),
    error: s.error ? stripAnsi(s.error.message || String(s.error)) : undefined,
    steps: children && children.length > 0 ? children : undefined,
  };
}

class HealixStepsReporter {
  constructor() {
    this.results = [];
  }

  onTestEnd(test, result) {
    const steps = (result.steps || []).filter((s) => KEPT_CATEGORIES.has(s.category)).map(toStepItem);
    if (steps.length === 0) return;
    this.results.push({ title: test.title, retry: result.retry, steps });
  }

  onEnd() {
    try {
      fs.writeFileSync(path.join(process.cwd(), 'steps.json'), JSON.stringify(this.results), 'utf-8');
    } catch {
      // best-effort — never fail the actual test run over this
    }
  }
}

module.exports = HealixStepsReporter;
`;
}

/**
 * Custom Playwright reporter that persists every FINISHED test's identity to
 * disk THE MOMENT it finishes, instead of buffering until onEnd() like
 * HealixStepsReporter above (which exists purely for cosmetic step detail and
 * can afford to lose everything on a crash). This file is what makes resuming
 * a killed/paused execution safe: execute.ts reads it back and passes
 * `--test-list-invert` on the next attempt so already-finished tests are never
 * re-run. Without a write-through reporter, a mid-run crash loses every result
 * Playwright already produced, forcing a resume to redo the entire suite from
 * scratch — the same problem that used to require one Playwright invocation
 * PER TIER just to get a coarse, tier-boundary checkpoint.
 *
 * Only appends once a test's fate is TRULY final — `result.status ===
 * 'passed'` (no more retries needed) OR `result.retry >= test.retries` (every
 * configured retry has been used) — never on an earlier failing attempt that
 * still has retries left. `test.outcome()` looks tempting for this, but it
 * reflects only the attempts seen SO FAR: verified empirically that a test
 * failing on attempt 1 of a 2-retry config already reports outcome() ===
 * 'unexpected', even though Playwright hasn't given up on it yet. Treating
 * that as final would wrongly skip a test on resume that deserved another
 * retry attempt.
 *
 * The key format ("[project] › file › describe › test") matches EXACTLY what
 * `npx playwright test --list` / `--test-list-invert` expect — verified
 * against a real Playwright run — built straight from test.titlePath() rather
 * than hand-reconstructed from file paths, so it stays correct across
 * Playwright versions rather than depending on this code guessing right.
 */
export function checkpointReporterContents(): string {
  return `const fs = require('node:fs');
const path = require('node:path');

const CHECKPOINT_FILE = ${JSON.stringify(EXEC_CHECKPOINT_FILENAME)};
// Same pattern as steps-reporter.cjs: Playwright's error messages carry
// terminal color escape codes by default — left unstripped they render as
// garbled control characters wherever this checkpoint's error text surfaces
// (e.g. a Tier B row restored from an interrupted attempt, in execute.ts's
// checkpointEntriesToOutcome).
const ANSI_RE = /[\\u001b\\u009b][[\\]()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g;
function stripAnsi(text) {
  return (text || '').replace(ANSI_RE, '');
}

function titleInfo(test) {
  const parts = test.titlePath().slice(1); // drop the leading '' root entry
  return {
    project: parts[0],
    specFile: parts[1],
    title: parts[parts.length - 1],
    key: '[' + parts[0] + '] \\u203a ' + parts.slice(1).join(' \\u203a '),
  };
}

class HealixCheckpointReporter {
  onTestEnd(test, result) {
    const isFinal = result.status === 'passed' || result.retry >= test.retries;
    if (!isFinal) return;
    try {
      const info = titleInfo(test);
      const errorText = result.error
        ? stripAnsi(result.error.stack || result.error.message || String(result.error))
        : undefined;
      const line =
        JSON.stringify({
          key: info.key,
          title: info.title,
          project: info.project,
          specFile: info.specFile,
          status: test.outcome(),
          durationMs: Math.round(result.duration || 0),
          error: errorText,
        }) + '\\n';
      fs.appendFileSync(path.join(process.cwd(), CHECKPOINT_FILE), line, 'utf-8');
    } catch {
      // best-effort — never fail the actual test run over this
    }
  }
}

module.exports = HealixCheckpointReporter;
`;
}

/**
 * Auth setup fixture. Requires Healix to have injected test credentials for
 * this project (single or multiple, via HEALIX_TIERB_* env vars); when none
 * are configured, or the DEFAULT credential's login attempt fails, this
 * throws immediately so Playwright marks every Tier B spec `blocked` right
 * away (via the `auth-setup` dependency) instead of each one individually
 * running to its own timeout against an anonymous session — Tier B has no
 * meaningful anonymous fallback. Additional (role-tagged) credentials each
 * get their own storageState file (fixtures/.auth/user-<role>.json); a
 * generated spec opts into one via test.use({ storageState: ... }) — see
 * generate.ts's role guidance — while everything else keeps using the
 * default session unchanged. A role credential's own login failure is
 * best-effort and never blocks the run; only specs that opt into that role
 * are affected.
 */
export function authSetupContents(): string {
  return `import { test as setup } from './action-highlighter.js';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';

const authDir = 'fixtures/.auth';
const authFile = \`\${authDir}/user.json\`;
// Sidecar read by Healix after the run: records whether a REAL login was
// performed (for the DEFAULT credential), so Tier B failures can be
// classified structurally (blocked vs genuine) instead of by matching error text.
const metaFile = \`\${authDir}/setup-meta.json\`;

async function writeMeta(performedLogin) {
  await writeFile(
    metaFile,
    JSON.stringify({ performedLogin, at: new Date().toISOString() }),
    'utf-8',
  );
}

function roleStorageStatePath(role) {
  const slug = role.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return \`\${authDir}/user-\${slug || 'role'}.json\`;
}

/**
 * getByLabel() only matches a REAL accessible label (an actual <label for=...>,
 * aria-label, or aria-labelledby) — plenty of real-world login forms show
 * "Email"/"Password" as plain sibling text (a <p> or <span> next to the
 * input, not an associated label) and rely on a placeholder for the
 * accessible name instead. Falling back through placeholder, then a plain
 * input[type=...]/name-contains selector, covers that gap without giving up
 * the label-based match as the FIRST choice when a form does it properly.
 */
function fieldLocator(page, labelRe, placeholderRe, cssFallback) {
  return page
    .getByLabel(labelRe)
    .or(page.getByPlaceholder(placeholderRe))
    .or(page.locator(cssFallback));
}

/**
 * A button's visible TEXT is the least reliable way to find it — it's
 * whatever the app is localized to (e.g. a Slovak app's submit button reads
 * "Pokračovať", which no English/Slovak text regex will anticipate). Native
 * submit semantics (type="submit") and test-hint attributes (data-testid/
 * name/id containing submit-like tokens) are locale-independent and take
 * priority; the text regex is kept only as a last-resort fallback for apps
 * with neither.
 *
 * Tiers are checked in order via .count() rather than chained with .or() —
 * .or() unions matches and .first() then picks whichever is FIRST IN DOM
 * ORDER, not first-matching-tier, so a hint selector broad enough to also
 * catch the email/password inputs (e.g. \`[data-testid*="login" i]\`) would
 * win over the real submit button simply for appearing earlier in the DOM.
 * Explicit per-tier existence checks keep priority correct.
 */
async function submitButtonLocator(page, textRe) {
  const native = page.locator('button[type="submit"], input[type="submit"]');
  if (await native.count()) return native.first();

  const hinted = page.locator(
    'button[data-testid*="submit" i], button[data-testid*="login" i], button[data-testid*="signin" i], button[data-testid*="continue" i], button[name*="submit" i], button[id*="submit" i], a[data-testid*="submit" i], a[data-testid*="login" i], a[data-testid*="signin" i], a[data-testid*="continue" i]',
  );
  if (await hinted.count()) return hinted.first();

  return page.getByRole('button', { name: textRe }).or(page.getByRole('link', { name: textRe })).first();
}

/**
 * Polls until the page navigates away from \`loginUrl\` or the password field
 * disappears, or 10s elapse. A real login is rarely a single synchronous
 * action — chained async calls (token generate -> password validate ->
 * profile lookup -> redirect) can easily outlast a single \`networkidle\`
 * check, so snapshotting immediately after the click can read the
 * pre-redirect state as success even when the submit click did nothing.
 */
async function waitForLoginOutcome(page, beforeUrl) {
  const deadline = Date.now() + 10_000;
  for (;;) {
    const stillHasPasswordField = await page
      .locator('input[type="password"]')
      .first()
      .isVisible()
      .catch(() => false);
    const navigatedAway = page.url() !== beforeUrl;
    if (navigatedAway || !stillHasPasswordField || Date.now() >= deadline) {
      return { navigatedAway, stillHasPasswordField };
    }
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
}

/**
 * One username/password form login against \`page\`, saving storageState to
 * \`path\` on success. Throws on failure — including when the submit click
 * "succeeded" (no exception) but the page never actually left the login
 * form, e.g. a wrong-password submit that just re-renders the same form
 * with an inline error. Without this check that would be indistinguishable
 * from a real login and would silently capture an anonymous storageState
 * that every downstream Tier B spec then fails against individually.
 */
async function loginForm(page, email, password, loginUrl, path) {
  await page.goto(loginUrl);

  // Locale-aware matchers (English + common Slovak forms observed in the
  // field, e.g. "e-mailová adresa" / "Heslo" / "Prihlásiť sa") — not a full
  // i18n engine, just enough to not be English-only.
  //
  // The login identifier field isn't always an email — plenty of real apps
  // (this one included) label it plain "Username", with no "email" anywhere
  // in the label, placeholder, or the input's name/id attributes either. An
  // /e-?mail/i-only matcher then finds nothing at all and hangs for the full
  // 60s test timeout with no selector-wait context, easily mistaken for an
  // environment/target problem rather than a selector gap. Matching
  // "username" (label/placeholder text) and the standards-based
  // autocomplete="username" attribute alongside email covers both shapes.
  const identifierField = fieldLocator(
    page,
    /e-?mail|user\\s*name/i,
    /e-?mail|user\\s*name/i,
    'input[type="email"], input[autocomplete="username"], input[name*="email" i], input[name*="user" i], input[id*="email" i], input[id*="user" i]',
  );
  const passwordField = fieldLocator(
    page,
    /heslo|password/i,
    /heslo|password/i,
    'input[type="password"]',
  );
  const loginRevealRe = /prihl|sign in|log ?in/i;

  // Some apps gate the login form behind a reveal button/link (e.g. a
  // "Prihlásiť sa" click before the identifier/password fields even render) —
  // click through it before searching for the form.
  const hasIdentifierField = await identifierField
    .first()
    .isVisible()
    .catch(() => false);
  if (!hasIdentifierField) {
    const reveal = await submitButtonLocator(page, loginRevealRe);
    await reveal.click({ timeout: 5000 }).catch(() => {});
  }

  await identifierField.first().fill(email);
  await passwordField.first().fill(password);
  const beforeUrl = page.url();
  const submitButton = await submitButtonLocator(page, /prihl|sign in|log ?in|continue/i);
  await submitButton.click();

  const { navigatedAway, stillHasPasswordField } = await waitForLoginOutcome(page, beforeUrl);
  if (stillHasPasswordField && !navigatedAway) {
    throw new Error(
      \`Login did not navigate away from the login page after submitting — still on \${page.url()} with a visible password field. Check credentials or selectors.\`,
    );
  }

  await page.waitForLoadState('networkidle').catch(() => {});
  await page.context().storageState({ path });
}

/**
 * Substitute \`{token}\` (always available, from the credential's own token
 * field) and every \`{<key>}\` in extraParams into urlTemplate, then visit the
 * resulting URL against baseUrl — for apps with no login FORM at all: a
 * token (and optionally other params, e.g. a mobile number/locale) delivered
 * via the URL itself, persisted to cookies/localStorage on first load.
 */
async function loginUrlToken(page, cred, baseUrl, path) {
  let target = cred.urlTemplate || '';
  const params = Object.assign({ token: cred.token || '' }, cred.extraParams || {});
  for (const [key, value] of Object.entries(params)) {
    target = target.split(\`{\${key}}\`).join(encodeURIComponent(value));
  }
  const base = (baseUrl || '').replace(/\\/+$/, '');
  const sep = target.startsWith('/') || target.startsWith('#') || target.startsWith('?') ? '' : '/';
  await page.goto(\`\${base}\${sep}\${target}\`);

  // Best-effort: wait for a transient "not found"/loading message to clear
  // (a signal the token resolved), but never hard-fail on it — the
  // storageState is still captured either way, since some apps never show
  // such a message at all.
  if (cred.authCheckText) {
    await page
      .getByText(cred.authCheckText, { exact: false })
      .first()
      .waitFor({ state: 'hidden', timeout: 15000 })
      .catch(() => {});
  } else {
    await page.waitForLoadState('networkidle').catch(() => {});
  }

  const state = await page.context().storageState({ path });
  if (state.cookies.length === 0 && state.origins.length === 0) {
    throw new Error(
      \`URL-token login produced an empty session (no cookies, no localStorage) at \${page.url()} — the token likely didn't resolve. Check the credential's urlTemplate/token.\`,
    );
  }
}

/** Dispatches to the right login mechanism for this credential's authType. */
async function login(page, cred, loginUrl, baseUrl, path) {
  if (cred.authType === 'url-token') {
    await loginUrlToken(page, cred, baseUrl, path);
  } else {
    await loginForm(page, cred.username, cred.password, loginUrl, path);
  }
}

setup('authenticate', async ({ page, browser }) => {
  await mkdir(dirname(authFile), { recursive: true });

  const email = process.env.HEALIX_TIERB_EMAIL;
  const password = process.env.HEALIX_TIERB_PASSWORD;
  const loginUrl = process.env.HEALIX_TIERB_LOGIN_URL;
  const baseUrl = process.env.HEALIX_BASE_URL;

  if (!email || !password || !loginUrl) {
    await writeMeta(false);
    throw new Error(
      'Tier B auth setup skipped: no test credentials configured for this project ' +
        '(and no HEALIX_TIERB_EMAIL/PASSWORD/LOGIN_URL env vars set). ' +
        'Set testUsername/testPassword on the project, or configure ' +
        'HEALIX_TIERB_EMAIL/HEALIX_TIERB_PASSWORD/HEALIX_TIERB_LOGIN_URL, to run Tier B tests.',
    );
  }

  const defaultCred = { authType: 'form', username: email, password, role: null };

  // Written BEFORE the login attempt so a mid-login crash still leaves
  // performedLogin:false on disk; overwritten with true only on success.
  await writeMeta(false);
  await login(page, defaultCred, loginUrl, baseUrl, authFile);
  await writeMeta(true);

  // Additional (role-tagged) credentials, via HEALIX_TIERB_CREDENTIALS_JSON —
  // each gets its own session, in a fresh browser context. Best-effort: one
  // credential's login failure doesn't stop the rest, and never blocks the
  // default Tier B session established above.
  let extraCredentials = [];
  try {
    extraCredentials = process.env.HEALIX_TIERB_CREDENTIALS_JSON
      ? JSON.parse(process.env.HEALIX_TIERB_CREDENTIALS_JSON)
      : [];
  } catch {
    extraCredentials = [];
  }
  // A credential is actually usable only if ITS OWN mechanism has what it
  // needs: a form credential needs loginUrl, a url-token credential needs
  // baseUrl (to resolve its urlTemplate against) — not both, and not
  // whichever one happens to be set globally.
  const usable = (c) => (c.authType === 'url-token' ? !!baseUrl : !!loginUrl);

  for (const cred of extraCredentials) {
    if (!cred.role || !usable(cred)) continue;
    const context = await browser.newContext();
    const rolePage = await context.newPage();
    try {
      await login(rolePage, cred, loginUrl, baseUrl, roleStorageStatePath(cred.role));
    } catch {
      // Best-effort: a role-specific login failure only affects specs that
      // opt into that role's storageState, not the default Tier B session.
    } finally {
      await context.close();
    }
  }
});
`;
}

/**
 * Fixture wrapping @playwright/test's `test`/`page` with an auto-injected
 * browser-side script that makes a recorded video actually show what a test
 * is doing: a fake cursor, a highlight ring around whatever was just
 * interacted with, and a floating banner naming the action. Generated specs
 * import { test, expect } from here instead of '@playwright/test' directly —
 * see generate.ts's ACTION_HIGHLIGHTER_IMPORT_PATH — so no changes are ever
 * needed to how a spec calls page/locator methods.
 *
 * Deliberately NOT a wrapper around Playwright's click()/fill()/etc. — there's
 * no supported way to intercept those (Locator isn't an exported class from
 * '@playwright/test'). Instead it passively watches real DOM events
 * (mousemove/pointerdown/focusin/scroll) that Playwright's own actions already
 * dispatch in the page, so it reacts to whatever a spec does without needing
 * to know how it did it.
 *
 * Adds NO artificial wait to the actual test run: the cursor/highlight/banner
 * animate via CSS transitions the browser plays out in real wall-clock time
 * while Playwright's script has already moved on to the next line — the
 * video, which is a continuous capture independent of what the test script is
 * doing, records them regardless.
 */
export function actionHighlighterFixtureContents(): string {
  return `import { test as base, expect } from '@playwright/test';

/**
 * Healix-generated visual action highlighter. Injected into every page via
 * addInitScript so it runs before any page script, on every navigation.
 */
function healixActionHighlighter() {
  if (window.__healixHighlighterInstalled) return;
  window.__healixHighlighterInstalled = true;

  var STYLE_ID = '__healix_highlighter_style';
  if (!document.getElementById(STYLE_ID)) {
    var style = document.createElement('style');
    style.id = STYLE_ID;
    style.textContent =
      '#__healix_cursor { position: fixed; width: 18px; height: 18px; border-radius: 50%;' +
      ' background: rgba(255,90,90,0.85); border: 2px solid #fff; box-shadow: 0 0 6px rgba(0,0,0,0.5);' +
      ' pointer-events: none; z-index: 2147483647; transition: left 100ms linear, top 100ms linear, opacity 150ms;' +
      ' transform: translate(-50%, -50%); opacity: 0; }' +
      '#__healix_banner { position: fixed; left: 50%; bottom: 24px; transform: translateX(-50%);' +
      ' background: rgba(20,20,24,0.88); color: #fff; font: 13px/1.4 -apple-system,Segoe UI,Roboto,sans-serif;' +
      ' padding: 6px 14px; border-radius: 999px; pointer-events: none; z-index: 2147483647;' +
      ' opacity: 0; transition: opacity 200ms; white-space: nowrap; }' +
      '#__healix_banner.show { opacity: 1; }' +
      '.__healix_highlight { position: fixed; border: 2px solid #ff5a5a; border-radius: 4px;' +
      ' box-shadow: 0 0 0 3px rgba(255,90,90,0.35); pointer-events: none; z-index: 2147483646;' +
      ' opacity: 0; transition: opacity 200ms; }' +
      '.__healix_highlight.show { opacity: 1; }';
    (document.head || document.documentElement).appendChild(style);
  }

  function ensureEl(id) {
    var el = document.getElementById(id);
    if (!el) {
      el = document.createElement('div');
      el.id = id;
      (document.body || document.documentElement).appendChild(el);
    }
    return el;
  }

  function describe(el) {
    if (!el || el.nodeType !== 1) return 'the page';
    var tag = el.tagName.toLowerCase();
    var label =
      el.getAttribute('aria-label') ||
      el.getAttribute('placeholder') ||
      el.getAttribute('name') ||
      (el.textContent || '').trim().slice(0, 40) ||
      el.id ||
      tag;
    if (tag === 'input' || tag === 'textarea') return 'field "' + label + '"';
    if (tag === 'select') return 'dropdown "' + label + '"';
    if (tag === 'button' || el.getAttribute('role') === 'button') return 'button "' + label + '"';
    if (tag === 'a') return 'link "' + label + '"';
    return '"' + label + '"';
  }

  var bannerTimer = null;
  function showBanner(text) {
    var banner = ensureEl('__healix_banner');
    banner.textContent = text;
    banner.classList.add('show');
    if (bannerTimer) clearTimeout(bannerTimer);
    bannerTimer = setTimeout(function () {
      banner.classList.remove('show');
    }, 900);
  }

  var highlightPool = [];
  function highlightElement(el) {
    if (!el || el.nodeType !== 1 || typeof el.getBoundingClientRect !== 'function') return;
    var rect = el.getBoundingClientRect();
    var box = highlightPool.pop();
    if (!box) {
      box = document.createElement('div');
      box.className = '__healix_highlight';
      (document.body || document.documentElement).appendChild(box);
    }
    box.style.left = rect.left - 3 + 'px';
    box.style.top = rect.top - 3 + 'px';
    box.style.width = rect.width + 6 + 'px';
    box.style.height = rect.height + 6 + 'px';
    box.classList.add('show');
    setTimeout(function () {
      box.classList.remove('show');
      setTimeout(function () {
        highlightPool.push(box);
      }, 250);
    }, 500);
  }

  document.addEventListener(
    'mousemove',
    function (e) {
      var cursor = ensureEl('__healix_cursor');
      cursor.style.left = e.clientX + 'px';
      cursor.style.top = e.clientY + 'px';
      cursor.style.opacity = '1';
    },
    true,
  );

  document.addEventListener(
    'pointerdown',
    function (e) {
      highlightElement(e.target);
      var tag = ((e.target && e.target.tagName) || '').toLowerCase();
      var verb = tag === 'a' ? 'Clicking' : tag === 'input' || tag === 'select' ? 'Interacting with' : 'Clicking';
      showBanner(verb + ' ' + describe(e.target));
    },
    true,
  );

  document.addEventListener(
    'focusin',
    function (e) {
      var tag = ((e.target && e.target.tagName) || '').toLowerCase();
      if (tag !== 'input' && tag !== 'textarea' && tag !== 'select') return;
      highlightElement(e.target);
      showBanner('Typing into ' + describe(e.target));
    },
    true,
  );

  var scrollTimer = null;
  document.addEventListener(
    'scroll',
    function () {
      if (scrollTimer) return;
      showBanner('Scrolling');
      scrollTimer = setTimeout(function () {
        scrollTimer = null;
      }, 400);
    },
    true,
  );

  window.addEventListener('beforeunload', function () {
    showBanner('Navigating…');
  });
}

export const test = base.extend({
  page: async ({ page }, use) => {
    await page.addInitScript(healixActionHighlighter);
    await use(page);
  },
});

export { expect };
`;
}

export interface MockRouteEntry {
  id: string;
  hostnames: string[];
  response: MockResponse;
  /** Statically-detected (method, path) call sites, when found — see EndpointMock. */
  endpoints?: Array<{ method: string; pathPattern: string; response?: MockResponse }>;
}

/**
 * Fixture wrapping @playwright/test's `test`/`page` with automatic page.route()
 * interception for every 'route-intercept'/'both' external dependency, fulfilling
 * with the (AI-generated or static-fallback) canned response resolved before
 * generation. Generated specs import { test, expect } from this file instead of
 * '@playwright/test' directly whenever mocking is enabled for the run — see
 * generate.ts's conditional import allowlist carve-out.
 *
 * Always written when mocking is enabled, even with an empty route list (a
 * harmless no-op passthrough), so generate.ts's import path always resolves
 * regardless of what was actually detected.
 */
export function mockFixtureContents(routes: MockRouteEntry[]): string {
  const serialized = JSON.stringify(routes, null, 2);
  return `import { test as base, expect } from './action-highlighter.js';

/**
 * Healix-generated mock fixture — intercepts network requests to detected
 * external dependencies (backend APIs, third-party SMS/email/OTP/payment SDKs)
 * and fulfills them with a canned response, so tests run without those
 * services being reachable.
 */

const MOCKED_ROUTES = ${serialized};

function hostMatches(url, pattern) {
  let parsed;
  try {
    parsed = new URL(url);
  } catch {
    return false;
  }
  if (pattern.includes(':')) return parsed.host === pattern;
  return parsed.hostname === pattern || parsed.hostname.endsWith('.' + pattern);
}

// \`:param\` segments (e.g. "/reward/:param") match any single path segment —
// see dependencies.ts's normalizeEndpointPath for how these are produced.
// Case-insensitive: a detected "/API/Foo" and a real request to "/api/foo"
// are the same endpoint to any real HTTP router.
function pathMatches(pattern, requestPath) {
  const patternSegs = pattern.split('/').filter(Boolean);
  const pathSegs = requestPath.split('/').filter(Boolean);
  if (patternSegs.length !== pathSegs.length) return false;
  return patternSegs.every(
    (seg, i) => seg === ':param' || seg.toLowerCase() === pathSegs[i].toLowerCase(),
  );
}

// Serialize a response body per its declared content-type — JSON.stringify
// only when the type is (or defaults to) JSON, so a deliberately non-JSON
// mocked response (text/xml/etc, body given as a raw string) isn't
// double-encoded.
function serializeBody(response) {
  const contentType = (response.headers && response.headers['content-type']) || 'application/json';
  if (!/json/i.test(contentType) && typeof response.body === 'string') {
    return { contentType, text: response.body };
  }
  return { contentType, text: JSON.stringify(response.body ?? {}) };
}

// Per-test runtime overrides set via the \`mockOverride\` fixture below — always
// checked FIRST, so a negative/error-path test (e.g. "simulate a 500") can
// force a specific status/body for one call without touching any other test
// or the shared static defaults. Reset after each test.
let overrides = [];

function resolveResponse(route, method, requestPath) {
  const override = overrides.find(
    (o) => o.method.toUpperCase() === method.toUpperCase() && pathMatches(o.pathPattern, requestPath),
  );
  if (override) return override.response;
  const endpoint = route.endpoints?.find(
    (e) => e.method.toUpperCase() === method.toUpperCase() && pathMatches(e.pathPattern, requestPath),
  );
  if (endpoint?.response) return endpoint.response;
  return route.response;
}

export const test = base.extend({
  // Lets a spec force a specific status/body for one (method, path) call,
  // scoped to just that test — e.g.
  //   mockOverride('GET', '/customer_lookup', { status: 500, body: {} })
  // Use this for negative/error-simulation tests (500/401/403/timeout-style
  // scenarios); everything else keeps using the resolved default response.
  // Malformed calls (wrong arg types) are ignored with a console.warn rather
  // than throwing, so a mistaken call degrades to "no override" instead of
  // crashing the whole test.
  mockOverride: async ({}, use) => {
    const fn = (method, pathPattern, response) => {
      if (typeof method !== 'string' || typeof pathPattern !== 'string' || !response || typeof response !== 'object') {
        console.warn('[mockOverride] ignored invalid call:', { method, pathPattern, response });
        return;
      }
      overrides.push({ method, pathPattern, response });
    };
    await use(fn);
    overrides = [];
  },
  page: async ({ page, mockOverride }, use) => {
    void mockOverride; // ensures overrides reset alongside this test via the fixture above
    for (const route of MOCKED_ROUTES) {
      await page.route(
        (url) => route.hostnames.some((h) => hostMatches(url.toString(), h)),
        async (r) => {
          let requestPath = '/';
          try {
            requestPath = new URL(r.request().url()).pathname;
          } catch {
            // keep default '/'
          }
          const response = resolveResponse(route, r.request().method(), requestPath);
          const { contentType, text } = serializeBody(response);
          await r.fulfill({
            status: response.status,
            headers: { 'content-type': contentType, ...(response.headers || {}) },
            body: text,
          });
        },
      );
    }
    await use(page);
  },
  // Playwright's page.route() only intercepts requests a BROWSER makes — it
  // cannot see calls made through the standalone \`request\` fixture (used by
  // API-contract-style specs), since that's a raw HTTP client with no
  // interception hooks at all. Fake it directly instead, matching by (method,
  // path) against the same route.endpoints/overrides resolution page uses
  // above. Only the first mocked dependency is served this way — request-
  // fixture calls use relative paths with no hostname to disambiguate between
  // multiple dependencies.
  request: async ({ request, mockOverride }, use) => {
    void mockOverride;
    if (MOCKED_ROUTES.length === 0) {
      await use(request);
      return;
    }
    const route = MOCKED_ROUTES[0];
    const respond = (method, requestPath) => {
      const canned = resolveResponse(route, method, (requestPath || '/').split('?')[0]);
      const { contentType, text } = serializeBody(canned);
      return {
        ok: () => canned.status >= 200 && canned.status < 300,
        status: () => canned.status,
        statusText: () => '',
        headers: () => ({ 'content-type': contentType, ...(canned.headers || {}) }),
        json: async () => canned.body ?? {},
        text: async () => text,
        body: async () => Buffer.from(text),
        url: () => requestPath || '',
        dispose: async () => undefined,
      };
    };
    const fakeRequest = {
      get: async (url) => respond('GET', url),
      post: async (url) => respond('POST', url),
      put: async (url) => respond('PUT', url),
      patch: async (url) => respond('PATCH', url),
      delete: async (url) => respond('DELETE', url),
      head: async (url) => respond('HEAD', url),
      options: async (url) => respond('OPTIONS', url),
      fetch: async (url, opts) => respond(opts?.method ?? 'GET', url),
      dispose: async () => undefined,
    };
    await use(fakeRequest);
  },
});

export { expect };
`;
}

/** Per-tier README placed in each tests/<tier> dir to keep the layout obvious. */
export function tierReadmeContents(tier: Tier): string {
  return `# ${tierLabel(tier)}

Generated Playwright specs for this tier live here.
Each spec title is tagged with [REQ:<id>] to trace back to a requirement.
`;
}

export interface SuiteReadmeOptions {
  baseUrl?: string | null;
}

/** Top-level README for the standalone, runnable suite. */
export function suiteReadmeContents(opts: SuiteReadmeOptions = {}): string {
  const baseUrl = (opts.baseUrl ?? '').trim() || 'http://localhost:3000';
  return `# Healix Playwright Suite

A standalone, runnable Playwright project generated by Healix.

## Run

\`\`\`bash
npm install
npx playwright install --with-deps
npx playwright test
\`\`\`

Set the target URL with \`HEALIX_BASE_URL\` (default: \`${baseUrl}\`).

## Tiers (Playwright projects)

- **${tierLabel('tierA-public')}** — \`tests/tierA-public\`
- **${tierLabel('tierB-auth')}** — \`tests/tierB-auth\` (uses \`fixtures/.auth/user.json\`)
- **${tierLabel('tierC-api')}** — \`tests/tierC-api\`

Run a single tier:

\`\`\`bash
npx playwright test --project=tierA-public
\`\`\`

## Reports

- \`results.json\` — machine-readable JSON report
- \`playwright-report/\` — HTML report (\`npx playwright show-report\`)
`;
}

/** Stable .gitignore so the exported suite doesn't carry local artifacts. */
export function gitignoreContents(): string {
  return `node_modules/
test-results/
playwright-report/
results.json
fixtures/.auth/
`;
}
